import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import HomepageImage from "../../public/homepage-img.avif";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <style jsx>
      {`
      h1{
        font-size: 50px;
      }
      h2{
        font-size: 38px;
      }
      h3{
        font-size: 24px;
      }
      p{
        font-size: 16px;
      }
      `}
    </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
      <main className={styles.main}>
        <div style={{ textAlign: 'center' }}>
          <h1>Hunting Coder</h1>
          <div className={styles.imageWrapper}>
            <Image className={styles.myimg} src={HomepageImage} width='237' height='158' />
          </div>
          <p>Blog for Hunting coders by a Hunting coder</p>
        </div>

        <div className={styles.blogs}>
          <h2>Latest blog</h2>
          <div className={styles.blogItems}>
            <h3>Best JavaScript course in 2022</h3>
            <p>Hunting coder JavaScript Course</p>
          </div>
          <div className={styles.blogItems}>
            <h3>Best JavaScript course in 2022</h3>
            <p>Hunting coder JavaScript Course</p>
          </div>
          <div className={styles.blogItems}>
            <h3>Best JavaScript course in 2022</h3>
            <p>Hunting coder JavaScript Course</p>
          </div>
          <div className={styles.blogItems}>
            <h3>Best JavaScript course in 2022</h3>
            <p>Hunting coder JavaScript Course</p>
          </div>
        </div>
      </main>
    </>
  )
}
